### ISSUE TITLE
Format for VideoExercises

### ISSUE THREAD

**Issue by ramnathv** [datacamp/courses-test-new-format#1]
I believe we should simplify the format for `VideoExercises`. The current exercise is written up as

    ## Analyze movie ratings

    ```yaml
    type: VideoExercise
    key: 58b94c3a47
    lang: r
    xp: 50
    skills: 1
    ```

    `@video_link`
    //player.vimeo.com/video/154783078

I believe, the `video_link` information should be a part of the metadata block.

    ## Analyze movie ratings

    ```yaml
    type: VideoExercise
    key: 58b94c3a47
    lang: r
    xp: 50
    skills: 1
    video_link: //player.vimeo.com/video/154783078
    ```
